server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  repo_path: /Users/getcharzp/Desktop/home/work/myself/git/gitee/kratos-gorm-git/repo
data:
  database:
    driver: mysql
    source: root:abcdi2124Jcke23@tcp(192.168.1.8:3306)/up-git?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
