// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"kratos-gorm-git/define"
	"kratos-gorm-git/internal/biz"
	"kratos-gorm-git/internal/conf"
	"kratos-gorm-git/internal/data"
	"kratos-gorm-git/internal/server"
	"kratos-gorm-git/internal/service"
	"net/http"

	server2 "github.com/asim/git-http-backend/server"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	// 1. 指定仓库地址
	server2.DefaultConfig.ProjectRoot = define.RepoPath
	server2.DefaultConfig.GitBinPath = "/usr/bin/git"
	// 2. 指定监听的服务
	http.HandleFunc("/git/", service.GitHttpBackend)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
